version: '2.4'

services:
  db:
    image: postgres:18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    env_file:
      - .env
    volumes:
      - ./apps/db:/var/lib/postgresql
    ports:
      - 5432:5432